# --- General Settings ---
set -g default-terminal "screen-256color"
set -g terminal-overrides ",xterm-256color:RGB"
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

set -g prefix C-a          # Swaps Ctrl-b to Ctrl-a
unbind C-b
bind-key C-a send-prefix

set -g base-index 1              # Start windows at 1
set -g pane-base-index 1         # Start panes at 1
set -g renumber-windows on       # Renumber windows when one is closed
set -g detach-on-destroy off     # Don't exit tmux when closing a session
set -g escape-time 0             # Zero-out escape time for Vim
set -g history-limit 1000000     # Increase history
set -g mouse on                  # Enable mouse support
set -g status-position bottom       # Move status bar to the top

# --- Keybindings ---
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Resize panes using Prefix + H, J, K, L (moves by 5 cells)
bind -r H resize-pane -L 60
bind -r J resize-pane -D 60
bind -r K resize-pane -U 60
bind -r L resize-pane -R 60

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'roosta/tmux-fuzzback'

# --- Plugin Config: SessionX ---
set -g @sessionx-bind 'o'           # Press Prefix + o to search sessions
set -g @sessionx-window-mode 'on'
set -g @sessionx-tree-mode 'on'

# --- Plugin Config: Catppuccin ---
set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, latte
set -g @catppuccin_window_status_style "rounded" # basic, rounded, slanted, custom, or none
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory" # date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.config/tmux/plugins/tpm/tpm'
